#ifndef COMMANDS_HPP
#define COMMANDS_HPP

// PREAMBLE
#define PREAMBLE0 0xFF
#define PREAMBLE1 0xFF
#define PREAMBLE2 0xFF
#define PREAMBLE3 0xFF

// COMMANDS
#define COMM_ID_START 0x01
#define COMM_ID_START_TIMEOUT 1000U
#define START_ANSWER_LENGTH 0U

#define COMM_ID_STOP 0x02
#define COMM_ID_STOP_TIMEOUT 1000U
#define STOP_ANSWER_LENGTH 10U

#define COMM_ID_START_CAN 0x03
#define COMM_ID_START_CAN_TIMEOUT 1000U
#define START_CAN_ANSWER_LENGTH 0U

#define COMM_ID_FRAME 0x04
#define COMM_ID_FRAME_TIMEOUT 1000U
#define FRAME_ANSRWER_LENGTH 37U

#define COMM_ID_STOP_CAN 0x05
#define COMM_ID_STOP_CAN_TIMEOUT 1000U
#define STOP_CAN_ANSWER_LENGTH 0U

#define COMM_ID_CAN_READ_DEV_ID 0x06
#define COMM_ID_CAN_READ_DEV_ID_TIMEOUT 1000U
#define CAN_READ_DEV_ID_ANSWER_LENGTH 0U

#define COMM_ID_CAN_WRITE_DEV_ID 0x07
#define COMM_ID_CAN_WRITE_DEV_ID_TIMEOUT 1000U
#define CAN_WRITE_DEV_ID_ANSWER_LENGTH 0U

#define COMM_ID_WRITE_CONFIG 0x08
#define COMM_ID_WRITE_CONFIG_TIMEOUT 1000U
#define WRITE_CONFIG_ANSWER_LENGTH 0U

#define COMM_ID_READ_CONFIG 0x09
#define COMM_ID_READ_CONFIG_TIMEOUT 1000U
#define READ_CONFIG_ANSWER_LENGTH 25U

#define COMM_ID_READ_FIRMWARE_VERSION 0x0A
#define COMM_ID_READ_FIRMWARE_VERSION_TIMEOUT 1000U
#define READ_FIRMWARE_VERSION_ANSWER_LENGTH 14U

#define COMM_ID_START_NO_PARAMS 0x0B
#define COMM_ID_START_NO_PARAMS_TIMEOUT 1000U
#define START_NO_PARAMS_ANSWER_LENGTH 0U

#define COMM_ID_RESET_JSON 0x0C
#define COMM_ID_RESET_JSON_TIMEOUT 1000U
#define RESET_JSON_ANSWER_LENGTH 0U

#define COMM_ID_WRITE_JSON 0x0D
#define COMM_ID_WRITE_JSON_TIMEOUT 1000U
#define WRITE_JSON_ANSWER_LENGTH 0U

#define COMM_ID_APPLY_JSON 0x0E
#define COMM_ID_APPLY_JSON_TIMEOUT 1000U
#define APPLY_JSON_ANSWER_LENGTH 0U

#define COMM_ID_GET_MATRIX_NAME 0x0F
#define COMM_ID_GET_MATRIX_NAME_TIMEOUT 1000U
#define GET_MATRIX_NAME_ANSWER_LENGTH 0U

#define COMM_ID_WRITE_WIFI_CONF 0x10
#define COMM_ID_WRITE_WIFI_CONF_TIMEOUT 1000U
#define WRITE_WIFI_CONF_ANSWER_LENGTH 0U

#define COMM_ID_READ_WIFI_CONF 0x11
#define COMM_ID_READ_WIFI_CONF_TIMEOUT 1000U
#define READ_WIFI_CONF_ANSWER_LENGTH 0U

#define COMM_ID_WRITE_FLTR_CONF 0x12
#define COMM_ID_WRITE_FLTR_CONF_TIMEOUT 1000U
#define WRITE_FLTR_CONF_ANSWER_LENGTH 0U

#define COMM_ID_READ_FLTR_CONF 0x13
#define COMM_ID_READ_FLTR_CONF_TIMEOUT 1000U
#define READ_FLTR_CONF_ANSWER_LENGTH 0U

#define COMM_ID_RESET_CALIBR 0x14
#define COMM_ID_RESET_CALIBR_TIMEOUT 1000U
#define RESET_CALIBR_ANSWER_LENGTH 0U

#define COMM_ID_WRITE_CALIBR_REF 0x15
#define COMM_ID_WRITE_CALIBR_REF_TIMEOUT 1000U
#define WRITE_CALIBR_REF_ANSWER_LENGTH 0U

#define COMM_ID_WRITE_CALIBR_TABLE 0x16
#define COMM_ID_WRITE_CALIBR_TABLE_TIMEOUT 1000U
#define WRITE_CALIBR_TABLE_ANSWER_LENGTH 0U

#define COMM_ID_READ_CALIBR 0x17
#define COMM_ID_READ_CALIBR_TIMEOUT 1000U
#define READ_CALIBR_ANSWER_LENGTH 0U

#define COMM_ID_READ_CALIBR_TABLE 0x18
#define COMM_ID_READ_CALIBR_TABLE_TIMEOUT 1000U
#define READ_CALIBR_TABLE_ANSWER_LENGTH 0U

#define COMM_ID_READ_CALIBR_COMPLETE 0x19
#define COMM_ID_READ_CALIBR_COMPLETE_TIMEOUT 1000U
#define READ_CALIBR_COMPLETE_ANSWER_LENGTH 0U

#define COMM_ID_WRITE_ACTIVE_CONF 0x1A
#define COMM_ID_WRITE_ACTIVE_CONF_TIMEOUT 1000U
#define WRITE_ACTIVE_CONF_ANSWER_LENGTH 0U

#define COMM_ID_READ_ACTIVE_CONF 0x1B
#define COMM_ID_READ_ACTIVE_CONF_TIMEOUT 1000U
#define READ_ACTIVE_CONF_ANSWER_LENGTH 0U

// REQUEST STATUS
#define SESSION_STARTED 0x00
#define SESSION_STOPED 0x01
//
#define SET_DATA_MODE   "DATA\r\n"

#endif // COMMANDS_HPP
